[package]
name = "filter_fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libafl = "0.7.0"
tensorflow = "0.17.0"
num-traits = "*"
clap = { version = "3.0.0-rc.4", features = ["default"] }