[package]
name = "filter_fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libafl = "0.6.1"
crossbeam = "0.8.1"   # channel
tensorflow = "0.17.0"
